### ISSUE TITLE
wifi用不了

### ISSUE THREAD

**Issue by 760644586** [stormeyes/android_kernel_xiaomi_nitrogen#1]

**Comment by stormeyes** [comment]
@760644586 你是编译我的这个repo里面代码吗? 不可能啊, 我已经把wifi代码加进去了, 之前编译过一次, WIFI是可用的. 把你的编译步骤贴一下

**Comment by 760644586** [comment]
不是的   我用的是小米4的

**Comment by stormeyes** [comment]
@760644586 你需要把qcacld-3.0的代码放进你的kernel里面, 稍微修改一下配置并重新编译就可以了.
具体的变更你可以查看我的这个commit https://github.com/stormeyes/android_kernel_xiaomi_nitrogen/commit/e970f103e7b0cfad538cec4f7c441afa7a8970e4

**Comment by 760644586** [comment]
用的这个内核源码:
https://github.com/MiCode/Xiaomi_Kernel_OpenSource/tree/cancro-m-oss

并且按照下面这个过程编译过也不行
https://github.com/MiCode/Xiaomi_Kernel_OpenSource/wiki/How-To-Use#download-qualcomm-android-enablement-project


平常的编译过程序是

export ANDROID_AARCH64=/home/admin/arm-eabi-4.6/bin/
export ARCH=arm
export SUBARCH=arm
export PATH=$PATH:$ANDROID_AARCH64
export CROSS_COMPILE=arm-eabi-
mkdir output
make O=output cancro_user_defconfig
cd output
make O=output

**Comment by 760644586** [comment]
去LineageOS下载对应版本型号的kernel源码

找到driver/staging/ 下复制了prima的文件夹到小米的内核里

在这个文件下/arch/arm/configs/cancro_user_defconfig
#
# Qualcomm Atheros Prima WLAN module
#
# CONFIG_PRIMA_WLAN is not set
CONFIG_PRONTO_WLAN=y
# CONFIG_PRIMA_WLAN_BTAMP is not set
CONFIG_PRIMA_WLAN_LFR=y
CONFIG_PRIMA_WLAN_OKC=y
CONFIG_PRIMA_WLAN_11AC_HIGH_TP=y
CONFIG_WLAN_FEATURE_11W=y
CONFIG_QCOM_VOWIFI_11R=y
CONFIG_ENABLE_LINUX_REG=y
我加入了以上代码
------------------------------------------------------------------------------

在这个文件下/drivers/staging/Makefile
obj-$(CONFIG_PRIMA_WLAN)    += prima/
obj-$(CONFIG_PRONTO_WLAN)    += prima/
我加入了以上代码
------------------------------------------------------------------------------


在这个文件下/drivers/staging/Kconfig
source "drivers/staging/prima/Kconfig"
我加入了以上代码
------------------------------------------------------------------------------


编译过后   wifi还是无法使用  也并没有编译出wlan.ko文件  只有wlan.o

求指点  求教育   谢谢
